Games = {
  ["FragPunk"] = { Binary = "FragPunk.exe", ["Core-Binding"] = { Mode = "X3D", SMT = false } },
  ["Cyberpunk 2077"] = { Binary = "Cyberpunk2077.exe", ["Core-Binding"] = { Mode = "X3D", SMT = false } },
  ["NFS 14"] = { Binary = "NFS14.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["WRC"] = { Binary = "WRC.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["NFS 11 Remastered"] = { Binary = "NFS11Remastered.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Need For Speed Unbound"] = { Binary = "NeedForSpeedUnbound.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Need For Speed Heat"] = { Binary = "NeedForSpeedHeat.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Quake Champions"] = { Binary = "QuakeChampions.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["sauerbraten wc"] = { Binary = "sauerbraten_wc.exe", ["Core-Binding"] = { Mode = "X3D", SMT = false }, ["Init-Wait"] = { WaitMs = 250 } },
  ["sauerbraten"] = { Binary = "sauerbraten.exe", ["Core-Binding"] = { Mode = "X3D" }, ["Init-Wait"] = { WaitMs = 250 } },
  ["AC Valhalla"] = { Binary = "ACValhalla.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Age Of Empires III DE"] = { Binary = "AgeOfEmpiresIIIDE.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Among Us"] = { Binary = "AmongUs.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Anno 1800"] = { Binary = "Anno1800.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Apex Legends"] = { Binary = "ApexLegends.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["ARK Survival Evolved"] = { Binary = "ARKSurvivalEvolved.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Assassins Creed Odyssey"] = { Binary = "AssassinsCreedOdyssey.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Baldurs Gate 3"] = { Binary = "BaldursGate3.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Battlefield 2042"] = { Binary = "Battlefield2042.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Battlefield V"] = { Binary = "BattlefieldV.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Black Desert Online"] = { Binary = "BlackDesertOnline.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Borderlands 3"] = { Binary = "Borderlands3.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Call Of Duty MW"] = { Binary = "CallOfDutyMW.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Call Of Duty Warzone"] = { Binary = "CallOfDutyWarzone.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Celeste"] = { Binary = "Celeste.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Civilization VI"] = { Binary = "CivilizationVI.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Control DX12"] = { Binary = "Control_DX12.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Counter Strike 2"] = { Binary = "CounterStrike2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["CS 2"] = { Binary = "cs2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Crusader Kings 3"] = { Binary = "CrusaderKings3.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Dark Souls III"] = { Binary = "DarkSoulsIII.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Death Stranding"] = { Binary = "DeathStranding.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Destiny 2"] = { Binary = "Destiny2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Diablo III"] = { Binary = "DiabloIII.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Disco Elysium"] = { Binary = "DiscoElysium.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Divinity Original Sin 2"] = { Binary = "DivinityOriginalSin2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Doom Eternal"] = { Binary = "DoomEternal.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["DOTA 2"] = { Binary = "DOTA2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Dragon Age Inquisition"] = { Binary = "DragonAgeInquisition.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Elden Ring"] = { Binary = "EldenRing.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Elite Dangerous"] = { Binary = "EliteDangerous.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Euro Truck Simulator 2"] = { Binary = "EuroTruckSimulator2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Fall Guys"] = { Binary = "FallGuys.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Fallout 4"] = { Binary = "Fallout4.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Fallout 76"] = { Binary = "Fallout76.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Far Cry 6"] = { Binary = "FarCry6.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["FIFA 22"] = { Binary = "FIFA22.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Final Fantasy XIV"] = { Binary = "FinalFantasyXIV.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Flight Simulator"] = { Binary = "FlightSimulator.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Forza Horizon 4"] = { Binary = "ForzaHorizon4.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Forza Horizon 5"] = { Binary = "ForzaHorizon5.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Fortnite"] = { Binary = "FortniteClient-Win64-Shipping.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Gears 5"] = { Binary = "Gears5.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Ghost Recon Breakpoint"] = { Binary = "GhostReconBreakpoint.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Ghost Runner"] = { Binary = "GhostRunner.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["GTA 5"] = { Binary = "GTA5.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Hades"] = { Binary = "Hades.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Halo Infinite"] = { Binary = "HaloInfinite.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Hearts Of Iron IV"] = { Binary = "HeartsOfIronIV.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Hitman 3"] = { Binary = "Hitman3.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Horizon Zero Dawn"] = { Binary = "HorizonZeroDawn.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Hunt Showdown"] = { Binary = "HuntShowdown.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Jurassic World Evolution 2"] = { Binary = "JurassicWorldEvolution2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Kerbal Space Program"] = { Binary = "KerbalSpaceProgram.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Kingdom Come Deliverance"] = { Binary = "KingdomComeDeliverance.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["League Of Legends"] = { Binary = "LeagueofLegends.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Madden NFL 21"] = { Binary = "MaddenNFL21.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Mass Effect Andromeda"] = { Binary = "MassEffectAndromeda.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Metro Exodus"] = { Binary = "MetroExodus.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Microsoft Flight Simulator"] = { Binary = "MicrosoftFlightSimulator.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Minecraft Launcher"] = { Binary = "MinecraftLauncher.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Monster Hunter World"] = { Binary = "MonsterHunterWorld.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Mortal Kombat 11"] = { Binary = "MortalKombat11.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Mount And Blade Bannerlord"] = { Binary = "MountAndBladeBannerlord.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["No Mans Sky"] = { Binary = "NoMansSky.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Outriders"] = { Binary = "Outriders.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Overwatch"] = { Binary = "Overwatch.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Path Of Exile"] = { Binary = "PathOfExile.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Phasmophobia"] = { Binary = "Phasmophobia.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["PUBG"] = { Binary = "PlayerUnknownsBattlegrounds.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Rainbow Six Siege"] = { Binary = "RainbowSixSiege.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["RDR 2"] = { Binary = "RDR2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Resident Evil 2"] = { Binary = "ResidentEvil2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Resident Evil Village"] = { Binary = "ResidentEvilVillage.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["RimWorld"] = { Binary = "RimWorld.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Risk Of Rain 2"] = { Binary = "RiskOfRain2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Rocket League"] = { Binary = "RocketLeague.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Satisfactory"] = { Binary = "Satisfactory.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Sekiro"] = { Binary = "Sekiro.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Shadow Of The Tomb Raider"] = { Binary = "ShadowOfTheTombRaider.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Sid Meiers Civilization VI"] = { Binary = "SidMeiersCivilizationVI.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Skyrim SE"] = { Binary = "SkyrimSE.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Smite"] = { Binary = "Smite.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Starcraft II"] = { Binary = "StarcraftII.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Stardew Valley"] = { Binary = "StardewValley.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Subnautica"] = { Binary = "Subnautica.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Terraria"] = { Binary = "Terraria.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["The Elder Scrolls Online"] = { Binary = "TheElderScrollsOnline.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["The Forest"] = { Binary = "TheForest.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["The Outer Worlds"] = { Binary = "TheOuterWorlds.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["The Sims 4"] = { Binary = "TheSims4.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["The Witcher 3 Wild Hunt"] = { Binary = "TheWitcher3WildHunt.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Total War Three Kingdoms"] = { Binary = "TotalWarThreeKingdoms.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Total War Warhammer 2"] = { Binary = "TotalWarWarhammer2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Total War Warhammer III"] = { Binary = "TotalWarWarhammerIII.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Valorant"] = { Binary = "Valorant.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Warframe"] = { Binary = "Warframe.x64.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Warhammer Vermintide 2"] = { Binary = "WarhammerVermintide2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Watch Dogs Legion"] = { Binary = "WatchDogsLegion.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Witcher 3"] = { Binary = "Witcher3.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["World Of Tanks"] = { Binary = "WorldOfTanks.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["World Of Warcraft"] = { Binary = "WorldOfWarcraft.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["World War Z"] = { Binary = "WorldWarZ.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["XCOM 2"] = { Binary = "XCOM2.exe", ["Core-Binding"] = { Mode = "X3D" } },
  ["Yakuza Like A Dragon"] = { Binary = "YakuzaLikeADragon.exe", ["Core-Binding"] = { Mode = "X3D" } },
}

function getGame(name)
  return Games[name]
end

gcb.clearGameList()

for name, data in pairs(Games) do
  gcb.addGame(name, data.Binary)
end
