-- This file is generated automatically by GCB. Do not edit manually.
Games = {
  ["A Plague Tale Innocence"] = { Binary = "APlagueTaleInnocence_x64.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["A Plague Tale Requiem"] = { Binary = "APlagueTaleRequiem_x64.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["AC Valhalla"] = { Binary = "ACValhalla.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true }, ["Init-Wait"] = { WaitMs = 0 } },
  ["ARK Survival Evolved"] = { Binary = "ARKSurvivalEvolved.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Age Of Empires III DE"] = { Binary = "AgeOfEmpiresIIIDE.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Alan Wake II"] = { Binary = "AlanWake2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Alone In The Dark"] = { Binary = "AloneInTheDark.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Amnesia The Bunker"] = { Binary = "AmnesiaTheBunker.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Among Us"] = { Binary = "AmongUs.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Anno 1800"] = { Binary = "Anno1800.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Apex Legends"] = { Binary = "ApexLegends.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assassins Creed IV Black Flag"] = { Binary = "AC4BFSP.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assassins Creed Odyssey"] = { Binary = "AssassinsCreedOdyssey.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true }, ["Init-Wait"] = { WaitMs = 0 } },
  ["Assassins Creed Origins"] = { Binary = "ACOrigins.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assassins Creed Syndicate"] = { Binary = "ACS.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assassins Creed Unity"] = { Binary = "ACUnity.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assetto Corsa"] = { Binary = "acs.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assetto Corsa Competizione"] = { Binary = "acc.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Assetto Corsa Ultimate Edition"] = { Binary = "acs.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Avatar Frontiers Of Pandora"] = { Binary = "AvatarFrontiers.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Babylons Fall"] = { Binary = "BabylonsFall.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Baldurs Gate 3"] = { Binary = "BaldursGate3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Banishers Ghosts Of New Eden"] = { Binary = "Banishers.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BattleBit Remastered"] = { Binary = "BattleBit.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield 1"] = { Binary = "bf1.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield 2"] = { Binary = "BF2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield 2042"] = { Binary = "Battlefield2042.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield 3"] = { Binary = "bf3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield 4"] = { Binary = "bf4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield Hardline"] = { Binary = "bfh.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Battlefield V"] = { Binary = "BattlefieldV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BioShock"] = { Binary = "Bioshock.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BioShock 2"] = { Binary = "Bioshock2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BioShock 2 Remastered"] = { Binary = "Bioshock2HD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BioShock Infinite"] = { Binary = "BioshockInfinite.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["BioShock Remastered"] = { Binary = "BioshockHD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Biomutant"] = { Binary = "Biomutant.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Black"] = { Binary = "black.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Black Desert Online"] = { Binary = "BlackDesertOnline.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Blasphemous"] = { Binary = "Blasphemous.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Blasphemous 2"] = { Binary = "Blasphemous2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Borderlands 2"] = { Binary = "Borderlands2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Borderlands 3"] = { Binary = "Borderlands3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Borderlands The Pre Sequel"] = { Binary = "BorderlandsPreSequel.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Braid"] = { Binary = "braid.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Brothers A Tale Of Two Sons"] = { Binary = "Brothers.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Bully"] = { Binary = "Bully.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Bully Scholarship Edition"] = { Binary = "Bully.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Burnout Paradise"] = { Binary = "BurnoutParadise.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Burnout Paradise Remastered"] = { Binary = "BurnoutPR.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["CS 2"] = { Binary = "cs2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Call Of Duty MW"] = { Binary = "CallOfDutyMW.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Call Of Duty Online"] = { Binary = "codol.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Call Of Duty Warzone"] = { Binary = "CallOfDutyWarzone.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Celeste"] = { Binary = "Celeste.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Chorus"] = { Binary = "Chorus.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Cities Skylines"] = { Binary = "Cities.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Cities Skylines II"] = { Binary = "Cities2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Civilization VI"] = { Binary = "CivilizationVI.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Code Vein"] = { Binary = "CodeVein.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Command And Conquer 3"] = { Binary = "CNC3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Command And Conquer 3 Kanes Wrath"] = { Binary = "CNC3EP1.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Command And Conquer 4"] = { Binary = "CNC4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Command And Conquer Remastered"] = { Binary = "CnCRemastered.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Control"] = { Binary = "Control.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Control DX12"] = { Binary = "Control_DX12.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Counter Strike 2"] = { Binary = "CounterStrike2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true }, ["Init-Wait"] = { WaitMs = 0 } },
  ["Crusader Kings III"] = { Binary = "ck3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Crysis"] = { Binary = "Crysis.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Crysis 2"] = { Binary = "Crysis2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Crysis 3"] = { Binary = "Crysis3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Cult Of The Lamb"] = { Binary = "CultOfTheLamb.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Cuphead"] = { Binary = "Cuphead.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Cyberpunk 2077"] = { Binary = "Cyberpunk2077.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = false } },
  ["DOOM The Dark Ages"] = { Binary = "DOOMTheDarkAges.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true } },
  ["DOTA 2"] = { Binary = "DOTA2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dark And Darker"] = { Binary = "DarkAndDarker.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dark Souls III"] = { Binary = "DarkSoulsIII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Darksiders Genesis"] = { Binary = "DarksidersGenesis.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Darksiders III"] = { Binary = "Darksiders3-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Days Gone"] = { Binary = "DaysGone.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Cells"] = { Binary = "deadcells.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Island 2"] = { Binary = "DeadIsland2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Island Definitive Edition"] = { Binary = "DeadIslandR.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Space"] = { Binary = "DeadSpace.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Space 2"] = { Binary = "DeadSpace2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Space 3"] = { Binary = "DeadSpace3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dead Space Remake"] = { Binary = "DeadSpaceRemake.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Death Stranding"] = { Binary = "DeathStranding.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Deathloop"] = { Binary = "Deathloop.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Destiny 2"] = { Binary = "Destiny2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Destroy All Humans"] = { Binary = "DAH.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Destroy All Humans 2 Reprobed"] = { Binary = "DAH2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Devil May Cry 5"] = { Binary = "DevilMayCry5.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Diablo III"] = { Binary = "DiabloIII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Disco Elysium"] = { Binary = "DiscoElysium.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dishonored"] = { Binary = "Dishonored.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dishonored 2"] = { Binary = "Dishonored2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Divinity Original Sin 2"] = { Binary = "DivinityOriginalSin2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Doom Eternal"] = { Binary = "DoomEternal.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon Age Inquisition"] = { Binary = "DragonAgeInquisition.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon Ball FighterZ"] = { Binary = "RED-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon Ball Xenoverse 2"] = { Binary = "DBXV2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon Ball Z Kakarot"] = { Binary = "DBZKakarot.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon Quest XI"] = { Binary = "DQVXI.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon's Dogma Dark Arisen"] = { Binary = "DDDA.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dragon's Dogma II"] = { Binary = "DragonsDogma2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Dungeon Keeper 2"] = { Binary = "DKII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["EA Sports FC 24"] = { Binary = "EASportsFC24.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Elden Ring"] = { Binary = "EldenRing.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Elden Ring Shadow Of The Erdtree"] = { Binary = "eldenring.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Elite Dangerous"] = { Binary = "EliteDangerous.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Escape From Tarkov"] = { Binary = "EscapeFromTarkov.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Euro Truck Simulator 2"] = { Binary = "EuroTruckSimulator2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Everspace 2"] = { Binary = "Everspace2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Exoprimal"] = { Binary = "Exoprimal.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["F1 23"] = { Binary = "F123.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["F1 24"] = { Binary = "F124.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FIFA 19"] = { Binary = "FIFA19.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FIFA 20"] = { Binary = "FIFA20.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FIFA 21"] = { Binary = "FIFA21.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FIFA 22"] = { Binary = "FIFA22.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FIFA Manager"] = { Binary = "Manager.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fall Guys"] = { Binary = "FallGuys.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fallout 3"] = { Binary = "Fallout3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fallout 4"] = { Binary = "Fallout4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fallout 76"] = { Binary = "Fallout76.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fallout New Vegas"] = { Binary = "FalloutNV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fallout Shelter"] = { Binary = "FalloutShelter.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Far Cry 3"] = { Binary = "FarCry3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Far Cry 4"] = { Binary = "FarCry4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Far Cry 5"] = { Binary = "FarCry5.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Far Cry 6"] = { Binary = "FarCry6.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Far Cry New Dawn"] = { Binary = "FarCryND.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fez"] = { Binary = "FEZ.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Final Fantasy VII Rebirth"] = { Binary = "ff7rebirth.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Final Fantasy VII Remake"] = { Binary = "ff7remake.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Final Fantasy XIV"] = { Binary = "FinalFantasyXIV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Final Fantasy XV"] = { Binary = "ffxv_s.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Final Fantasy XVI"] = { Binary = "ff16.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Flight Simulator"] = { Binary = "FlightSimulator.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Fortnite"] = { Binary = "FortniteClient-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Forza Horizon 4"] = { Binary = "ForzaHorizon4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Forza Horizon 5"] = { Binary = "ForzaHorizon5.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["FragPunk"] = { Binary = "FragPunk.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = false } },
  ["GTA 5"] = { Binary = "GTA5.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["GTA III"] = { Binary = "gta3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["GTA IV"] = { Binary = "GTAIV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["GTA San Andreas"] = { Binary = "gta-sa.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["GTA Trilogy DE"] = { Binary = "SanAndreas_DE.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["GTA Vice City"] = { Binary = "gta-vc.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Gears 5"] = { Binary = "Gears5.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Gears Tactics"] = { Binary = "GearTactics.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Genshin Impact"] = { Binary = "GenshinImpact.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Ghost Recon Breakpoint"] = { Binary = "GhostReconBreakpoint.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Ghost Runner"] = { Binary = "GhostRunner.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["God Of War"] = { Binary = "GodOfWar.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Gwent The Witcher Card Game"] = { Binary = "Gwent.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hades"] = { Binary = "Hades.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Half-Life 2"] = { Binary = "hl2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Halo Infinite"] = { Binary = "HaloInfinite.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Halo The Master Chief Collection"] = { Binary = "MCC-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hearts Of Iron IV"] = { Binary = "HeartsOfIronIV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hell Let Loose"] = { Binary = "HellLetLoose.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Helldivers"] = { Binary = "helldivers.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Helldivers 2"] = { Binary = "Helldivers2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hi Fi Rush"] = { Binary = "HiFiRush.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hi-Fi Rush"] = { Binary = "HiFiRush.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hitman 3"] = { Binary = "Hitman3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hogwarts Legacy"] = { Binary = "HogwartsLegacy.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hollow Knight"] = { Binary = "hollow_knight.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Honkai Impact 3rd"] = { Binary = "HonkaiImpact3rd.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Honkai Star Rail"] = { Binary = "StarRail.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Honor Of Kings"] = { Binary = "HonorOfKings.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Horizon Zero Dawn"] = { Binary = "HorizonZeroDawn.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hotline Miami"] = { Binary = "HotlineMiami.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hotline Miami 2"] = { Binary = "HotlineMiami2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Hunt Showdown"] = { Binary = "HuntShowdown.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["INSIDE"] = { Binary = "inside.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["It Takes Two"] = { Binary = "ItTakesTwo.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Jurassic World Evolution 2"] = { Binary = "JurassicWorldEvolution2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Justice Online"] = { Binary = "JusticeOnline.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Katana ZERO"] = { Binary = "KatanaZERO.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kerbal Space Program"] = { Binary = "KerbalSpaceProgram.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kerbal Space Program 2"] = { Binary = "KSP2_x64.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kingdom Classic"] = { Binary = "Kingdom.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kingdom Come Deliverance"] = { Binary = "KingdomComeDeliverance.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kingdom Two Crowns"] = { Binary = "KingdomTwoCrowns.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Kingdoms Of Amalur Re-Reckoning"] = { Binary = "KoAReReckoning.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["L.A. Noire"] = { Binary = "LANoire.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["League Of Legends"] = { Binary = "LeagueofLegends.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Left 4 Dead 2"] = { Binary = "left4dead2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Lies Of P"] = { Binary = "LiesOfP.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Limbo"] = { Binary = "limbo.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Loop Hero"] = { Binary = "Loop Hero.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Madden NFL 21"] = { Binary = "MaddenNFL21.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mafia Definitive Edition"] = { Binary = "MafiaDE.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mafia II Definitive Edition"] = { Binary = "MafiaII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mafia III"] = { Binary = "Mafia3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Manhunt"] = { Binary = "Manhunt.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Manhunt 2"] = { Binary = "Manhunt2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Manor Lords"] = { Binary = "ManorLords.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mass Effect Andromeda"] = { Binary = "MassEffectAndromeda.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Max Payne 2"] = { Binary = "MaxPayne2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Max Payne 3"] = { Binary = "MaxPayne3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Medal Of Honor"] = { Binary = "MOH.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Medal Of Honor Warfighter"] = { Binary = "MOHW.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Metro 2033 Redux"] = { Binary = "Metro2033.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Metro Exodus"] = { Binary = "MetroExodus.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Metro Last Light Redux"] = { Binary = "MetroLL.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Microsoft Flight Simulator"] = { Binary = "MicrosoftFlightSimulator.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Microsoft Mahjong"] = { Binary = "Mahjong.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Microsoft Solitaire Collection"] = { Binary = "Solitaire.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Midnight Club 2"] = { Binary = "MC2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Midnight Club LA"] = { Binary = "MCLA.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Miles Morales"] = { Binary = "MilesMorales.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Minecraft Launcher"] = { Binary = "MinecraftLauncher.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mirror's Edge"] = { Binary = "MirrorsEdge.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mirror's Edge Catalyst"] = { Binary = "MirrorsEdgeCatalyst.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Monster Hunter Rise"] = { Binary = "MonsterHunterRise.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Monster Hunter World"] = { Binary = "MonsterHunterWorld.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mortal Kombat 11"] = { Binary = "MortalKombat11.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Mount And Blade Bannerlord"] = { Binary = "MountAndBladeBannerlord.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["NBA 2K24"] = { Binary = "NBA2K24.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["NBA Live 08"] = { Binary = "NBALive08.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["NFS 11 Remastered"] = { Binary = "NFS11Remastered.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["NFS 14"] = { Binary = "NFS14.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Naraka Bladepoint"] = { Binary = "NarakaBladepoint.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Naruto Shippuden Ultimate Ninja Storm 4"] = { Binary = "NSUNS4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Heat"] = { Binary = "NeedForSpeedHeat.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Most Wanted 2005"] = { Binary = "speed.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Most Wanted 2012"] = { Binary = "NFS13.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Payback"] = { Binary = "NeedForSpeedPayback.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true } },
  ["Need For Speed Shift"] = { Binary = "shift.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Shift 2"] = { Binary = "shift2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed The Run"] = { Binary = "NFSRun.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Unbound"] = { Binary = "NeedForSpeedUnbound.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Need For Speed Underground 2"] = { Binary = "speed2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true }, ["Init-Wait"] = { WaitMs = 0 } },
  ["Nier Automata"] = { Binary = "NieRAutomata.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Nier Replicant"] = { Binary = "NieRReplicant.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["No Mans Sky"] = { Binary = "NoMansSky.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Oblivion"] = { Binary = "Oblivion.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Octopath Traveler"] = { Binary = "Octopath_Traveler.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Octopath Traveler II"] = { Binary = "OctopathTraveler2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["One Piece Odyssey"] = { Binary = "OnePieceOdyssey.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Ori And The Blind Forest"] = { Binary = "OriAndTheBlindForest.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Ori And The Will Of The Wisps"] = { Binary = "OriAndTheWilloftheWisps.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Outer Wilds"] = { Binary = "OuterWilds.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Outriders"] = { Binary = "Outriders.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Overcooked"] = { Binary = "Overcooked.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Overcooked 2"] = { Binary = "Overcooked2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Overwatch"] = { Binary = "Overwatch.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Oxenfree"] = { Binary = "Oxenfree.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["P3 Reload"] = { Binary = "P3R.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["PGA Tour 2K24"] = { Binary = "PGATOUR2K24.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["PUBG"] = { Binary = "PlayerUnknownsBattlegrounds.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Palworld"] = { Binary = "Palworld.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Papers Please"] = { Binary = "PapersPlease.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Path Of Exile"] = { Binary = "PathOfExile.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Persona 3 Reload"] = { Binary = "P3R.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Persona 5 Royal"] = { Binary = "P5R.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Phasmophobia"] = { Binary = "Phasmophobia.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Plants Vs Zombies Battle For Neighborville"] = { Binary = "PvZBfN.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Portal"] = { Binary = "portal.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Portal 2"] = { Binary = "portal2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Prey"] = { Binary = "Prey.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Psychonauts 2"] = { Binary = "Psychonauts2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Quake Champions"] = { Binary = "QuakeChampions.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["RDR 2"] = { Binary = "RDR2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Rainbow Six Siege"] = { Binary = "RainbowSixSiege.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Ratchet And Clank Rift Apart"] = { Binary = "RiftApart.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Red Alert 2"] = { Binary = "RA2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Red Alert 2 Yuri's Revenge"] = { Binary = "YURI.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Red Alert 3"] = { Binary = "RA3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Red Alert 3 Uprising"] = { Binary = "RA3_1.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Red Dead Redemption"] = { Binary = "RedDeadRedemption.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Remnant II"] = { Binary = "Remnant2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil 0"] = { Binary = "RE0HD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil 2"] = { Binary = "ResidentEvil2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil 3"] = { Binary = "re3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil 4 Remake"] = { Binary = "re4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil 7"] = { Binary = "re7.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil HD Remaster"] = { Binary = "BHReHD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Resident Evil Village"] = { Binary = "ResidentEvilVillage.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Returnal"] = { Binary = "Returnal.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["RimWorld"] = { Binary = "RimWorld.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Risk Of Rain 2"] = { Binary = "RiskOfRain2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Rocket League"] = { Binary = "RocketLeague.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Saints Row 2022"] = { Binary = "SaintsRow.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Saints Row IV Re-Elected"] = { Binary = "SaintsRowIV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Saints Row The Third Remastered"] = { Binary = "SaintsRowTheThird.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Satisfactory"] = { Binary = "Satisfactory.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Sauerbraten"] = { Binary = "sauerbraten.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = false }, ["Init-Wait"] = { WaitMs = 250 } },
  ["Sauerbraten WC"] = { Binary = "sauerbraten_wc.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = false }, ["Init-Wait"] = { WaitMs = 250 } },
  ["Scarlet Nexus"] = { Binary = "ScarletNexus.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Sea Of Solitude"] = { Binary = "SeaOfSolitude.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Sekiro"] = { Binary = "Sekiro.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Shadow Of The Tomb Raider"] = { Binary = "ShadowOfTheTombRaider.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Sid Meiers Civilization VI"] = { Binary = "SidMeiersCivilizationVI.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["SimCity 2013"] = { Binary = "SimCity.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["SimCity 4 Deluxe"] = { Binary = "SimCity 4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Skyrim SE"] = { Binary = "SkyrimSE.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Slay The Spire"] = { Binary = "SlayTheSpire.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Smite"] = { Binary = "Smite.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["SnowRunner"] = { Binary = "SnowRunner.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Sonic Frontiers"] = { Binary = "SonicFrontiers.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Spec Ops The Line"] = { Binary = "SpecOpsTheLine.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Spider Man Remastered"] = { Binary = "SpiderMan.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["SpongeBob SquarePants Battle For Bikini Bottom Rehydrated"] = { Binary = "SpongeBobRehydrated.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Spore"] = { Binary = "SporeApp.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Star Wars Jedi Survivor"] = { Binary = "SWJediSurvivor.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Starcraft II"] = { Binary = "StarcraftII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Stardew Valley"] = { Binary = "StardewValley.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Starfield"] = { Binary = "Starfield.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["State Of Decay 2"] = { Binary = "StateOfDecay2-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Stellaris"] = { Binary = "stellaris.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Stray"] = { Binary = "Stray-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Street Fighter 6"] = { Binary = "StreetFighter6.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Street Fighter V"] = { Binary = "StreetFighterV.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Subnautica"] = { Binary = "Subnautica.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["System Shock Remake"] = { Binary = "SystemShock.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Tell Me Why"] = { Binary = "TellMeWhy-Win64-Shipping.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Terraria"] = { Binary = "Terraria.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D, SMT = true }, ["Init-Wait"] = { WaitMs = 5000 } },
  ["The Binding Of Isaac Rebirth"] = { Binary = "isaac-ng.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Crew"] = { Binary = "TheCrew.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Crew 2"] = { Binary = "TheCrew2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Elder Scrolls III Morrowind"] = { Binary = "Morrowind.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Elder Scrolls Online"] = { Binary = "TheElderScrollsOnline.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Escapists"] = { Binary = "TheEscapists.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Escapists 2"] = { Binary = "TheEscapists2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Finals"] = { Binary = "TheFinals.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The First Descendant"] = { Binary = "TheFirstDescendant.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Forest"] = { Binary = "TheForest.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Last Of Us Part I"] = { Binary = "TheLastOfUsPartI.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Outer Worlds"] = { Binary = "TheOuterWorlds.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Sims 2"] = { Binary = "Sims2EP9.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Sims 3"] = { Binary = "TS3W.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Sims 4"] = { Binary = "TheSims4.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Witcher 2 Assassins Of Kings"] = { Binary = "witcher2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Witcher 3 Wild Hunt"] = { Binary = "TheWitcher3WildHunt.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Witcher Enhanced Edition"] = { Binary = "witcher.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["The Witness"] = { Binary = "TheWitness64_d3d11.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Thronebreaker The Witcher Tales"] = { Binary = "Thronebreaker.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Tiger Woods PGA Tour 08"] = { Binary = "TW08.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["TopSpin 2K25"] = { Binary = "TopSpin2K25.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Total War Shogun 2"] = { Binary = "Shogun2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Total War Three Kingdoms"] = { Binary = "TotalWarThreeKingdoms.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Total War Warhammer 2"] = { Binary = "TotalWarWarhammer2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Total War Warhammer III"] = { Binary = "TotalWarWarhammerIII.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Undertale"] = { Binary = "undertale.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Unravel"] = { Binary = "Unravel.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Unravel Two"] = { Binary = "Unravel2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Valorant"] = { Binary = "Valorant.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["WRC"] = { Binary = "WRC.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["WWE 2K24"] = { Binary = "WWE2K24.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Warframe"] = { Binary = "Warframe.x64.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Warhammer Vermintide 2"] = { Binary = "WarhammerVermintide2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Warhaven"] = { Binary = "Warhaven.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Watch Dogs"] = { Binary = "WatchDogs.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Watch Dogs 2"] = { Binary = "WatchDogs2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Watch Dogs Legion"] = { Binary = "WatchDogsLegion.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["What Remains Of Edith Finch"] = { Binary = "EdithFinch.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Wild Hearts"] = { Binary = "WildHearts.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Witcher 3"] = { Binary = "Witcher3.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Wo Long Fallen Dynasty"] = { Binary = "WoLong.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["World Of Tanks"] = { Binary = "WorldOfTanks.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["World Of Warcraft"] = { Binary = "WorldOfWarcraft.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["World War Z"] = { Binary = "WorldWarZ.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Worms W.M.D"] = { Binary = "wormsWMD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["XCOM 2"] = { Binary = "XCOM2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["XCOM Chimera Squad"] = { Binary = "Chimera.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["XCOM Enemy Unknown"] = { Binary = "XComEW.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["XDefiant"] = { Binary = "XDefiant.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Yakuza 0"] = { Binary = "Yakuza0.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Yakuza Kiwami"] = { Binary = "YakuzaKiwami.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Yakuza Kiwami 2"] = { Binary = "YakuzaKiwami2.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
  ["Yakuza Like A Dragon"] = { Binary = "YakuzaLAD.exe", ["Core-Binding"] = { Mode = gcb.CoreBindingMode.X3D } },
}
